# Adjust this config using utils/test_crop_adjuster for your device

small:
  cell_cols: 10
  cell_rows: 9
  frame_size:
    width: 1920
    height: 1080
  crop_size:
    width: 780
    height: 702
  absolute_values:
    lpx: 560
    rpx: 1340
    tpx: 279
    bpx: 981
  percs:
    left: 29.2
    right: 69.8
    top: 25.8
    bottom: 90.8